{{- if eq .Values.networkPolicy.flavor "cilium" -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
    - world
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: coredns
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: k8s-dns-node-cache
    toPorts:
    - ports:
      - port: "1053"
        protocol: UDP
      - port: "1053"
        protocol: TCP
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/component: ruler
        app.kubernetes.io/name: mimir
        io.kubernetes.pod.namespace: mimir
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
  endpointSelector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  ingress:
  - toPorts:
    - ports:
      - port: "8080"
        protocol: TCP
{{- end }}
