{{- if .Values.extraSecret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "grafana-agent-secret" .Values.extraSecret.name |  }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.extraSecret.annotations }}
  annotations:
  {{ toYaml .Values.extraSecret.annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.extraSecret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
