{{- if and .Values.vintageCluster.is (index .Values "grafana-agent").agent.securityContext.privileged }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name}}-agent-patch
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
rules:
  - nonResourceURLs: 
      - "/metrics"
    verbs:
      - get
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - "extensions"
    resourceNames:
      - pyroscope-agent
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "monitoring.coreos.com"
      - "monitoring.grafana.com"
      - "networking.k8s.io"
    resources:
      - configmaps
      - endpoints
      - endpointslices
      - events
      - ingresses
      - namespaces
      - nodes
      - nodes/metrics
      - nodes/proxy
      - pods
      - pods/log
      - secrets
      - services
      - podmonitors
      - probes
      - prometheusrules
      - servicemonitors
      - podlogs
    verbs:
      - get
      - list
      - watch
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-agent-patch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name}}-agent-patch
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name}}-agent-patch
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name}}-agent-patch
    namespace: {{ .Release.Namespace }}
{{- end }}
