global:
  image:
    registry: gsoci.azurecr.io

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

networkPolicy:
  flavor: cilium

serviceAccount:
  create: true

vintageCluster:
  is: false
  patchJob:
    image:
      name: giantswarm/kubectl
      tag: 1.28.4
      pullPolicy: IfNotPresent

## ExtraSecret can be used to store various data in an extra secret
## For instance, we can use it to store logging credentials in order to push data to a logging system:
## data:
##   url: <logging url where to send data>
##   username: <user with write access>
##   password: <user password>
extraSecret:
  # name: <secret name where are stored those credentials>
  annotations: {}
  data: {}

grafana-agent:
  image:
    repository: giantswarm/grafana-agent
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true

  agent:
    securityContext:
      privileged: false

  serviceAccount:
    create: true
