global:
  image:
    registry: docker.io

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

grafana-agent:
  agent:
    loggingSecret:
      enabled: false

  image:
    # -- Grafana Agent image repository.
    repository: giantswarm/grafana-agent
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true
