global:
  image:
    registry: docker.io

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

# Block to manage a secret with logging credentials in order to push data to logging system
loggingSecret:
  enabled: false
  ## Those values are set by the logging-operator because there are related to the cluster
  # secretName: <secret name where are stored those credentials>
  # url: <Loki url where to send data>
  # tenantId: <Tenant ID>
  # username: <user with write access>
  # password: <user password>

grafana-agent:
  image:
    # -- Grafana Agent image repository.
    repository: giantswarm/grafana-agent
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true
