global:
  image:
    registry: docker.io

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

# Block to manage a secret with logging credentials in order to push data to logging system
loggingSecret:
  enabled: false

grafana-agent:
  image:
    # -- Grafana Agent image repository.
    repository: giantswarm/grafana-agent
  configReloader:
    image:
      repository: giantswarm/configmap-reload

  serviceMonitor:
    enabled: true
