name: 'e2e-test: install chart on kind'
on: pull_request

jobs:
  test-install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.9.0  

      - name: install chart
        run: |
          helm dependency update ./helm/grafana-agent/
      
          kubectl --context kind-chart-testing apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.65.1/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

          helm --kube-context kind-chart-testing install e2e-test-grafana-agent ./helm/grafana-agent/ --wait --set networkPolicy.flavor=kubernetes

          kubectl --context kind-chart-testing wait pod --for=condition=Ready -l app.kubernetes.io/name=grafana-agent

          sleep 120

          STATE=$(kubectl --context kind-chart-testing get pods -l app.kubernetes.io/name=grafana-agent -ojson | jq -r '.items | .[0].status.phase')
          if [ "$STATE" == "Running" ]; then
              echo 'grafana agent is Running'
          else
              echo 'Error grafana agent is not Running' >&2
              exit 1
          fi
